baseurl = "https://www.stevebacher.com"
buildFuture = true
disableAliases = true
googleAnalytics = "UA-111445999-1"
languageCode = "en-us"
log = false
metaDataFormat = "yaml"
newContentEditor = "atom"
paginate = 30
theme = "tnd-base-layouts"
themesDir = "layouts-base"
title = "Steve Bacher - Progressive Democrat for Pennsylvania's 1st Congressional District"
[author]
name = ""
[blackfriday]
hrefTargetBlank = true
[mediaTypes."text/netlify"]
delimiter = ""
suffix = ""
[[menu.main]]
name = "Media"
url = "/media"
weight = 1
[[menu.main]]
identifier = "events"
name = "Events"
url = "/event/"
weight = 5
[[menu.main]]
identifier = "news"
name = "News"
url = "/news/"
weight = 4
[[menu.main]]
identifier = "endorsements"
name = "Endorsements"
url = "/endorsement/"
weight = 2
[[menu.main]]
identifier = "issues"
name = "Issues"
url = "/issue/"
weight = 3
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1
[outputFormats.HEADERS]
baseName = "_headers"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputFormats.REDIRECTS]
baseName = "_redirects"
isPlainText = true
mediatype = "text/netlify"
notAlternative = true
[outputs]
home = ["HTML", "HEADERS", "REDIRECTS"]
[params]
address_footer = "Friends of Steve Bacher &bull; PO Box 188 &bull; Morrisville, PA 19067 &bull; info@stevebacher.com"
copy_footer = "PAID FOR BY FRIENDS OF STEVE BACHER"
description = "Local activist and lifelong progressive Democrat Steve Bacher is running in the Democratic Primary, May 15, 2018, to represent Congressional district PA01 (Bucks and Montgomery Counties) in the U.S. House of Representatives."
donate_link = "https://secure.actblue.com/donate/steve-bacher-for-congress-1"
home_page_quote = "2018 will be the year Democrats, Independents, and awakened members of the other parties take back the Congress. We can do this together. We must do it for ourselves, and for our children and our grandchildren. Let’s work together to make it so. <br />—Steve Bacher"
images = ["/uploads/Steve_social_share_image_with_Logo-1200x.jpg"]
title_footer = "Steve Bacher"
[params.dev]
css_path = "/static/dist/css"
js_path = "/static/dist/js"
[params.styles]
background_color_class = "accent-color-dark"
body = "bg-near-white center site-fontTK sans-serif mid-gray mw9"
color_classes = "black bg-black"
[social]
facebook = "SteveBacherForCongress"
instagram = "stevebachercongress"
twitter = "SteveBacher"
[taxonomies]
category = "categories"
