
title = "Steve Bacher for Congress"
baseurl = "https://www.stevebacher.com"
metaDataFormat = "yaml"
themesDir = "layouts-base"
theme = "tnd-base-layouts"
googleAnalytics = "UA-xxxxx-1"
paginate = 30
buildFuture = true
log = false

#Set Disable Aliases to true to use Netlify Redirect headers
disableAliases = true
#SectionPagesMenu = "main"
newContentEditor = "atom"

languageCode = "en-us"

[social]
  twitter = ""
  facebook = "SteveBacherForCongress"
  #youtube = ""
  #instagram = ""

[author]
  name = ""

[outputs]
  home = ["HTML", "HEADERS", "REDIRECTS"]

[mediaTypes]
[mediaTypes."text/netlify"]
  suffix = ""
  delimiter = ""
[outputFormats]
[outputFormats.REDIRECTS]
  mediatype = "text/netlify"
  baseName = "_redirects"
  isPlainText = true
  notAlternative = true
[outputFormats.HEADERS]
  mediatype = "text/netlify"
  baseName = "_headers"
  isPlainText = true
  notAlternative = true


[params]
  description = ""
  copy_footer = "PAID FOR BY FRIENDS OF STEVE BACHER"

[params.styles]
  body = "bg-white center site-fontTK sans-serif mid-gray mw9"
  color_classes = "black bg-black"
  background_color_class = "accent-color-dark"


[params.dev]
  js_path = "/static/dist/js"
  css_path = "/static/dist/css"

[taxonomies]
  #tag = "tags"
  #category = "categories"
[[menu.main]]
  name = "About Steve"
  weight = 1
  identifier = "about"
  url = "/about/"

[[menu.main]]
  name = "Contact"
  weight = 2
  identifier = "contact"
  url = "/contact/"

  [[menu.main]]
    name = "News"
    weight = 2
    identifier = "news"
    url = "/news/"

# [[menu.main]]
#   name = "Get Involved"
#   weight = 1
#   identifier = "get-involved"
#   url = "/get-involved/"
