---
upload_path: "/static/uploads/"
frontmatter_file_url_template: "/uploads/"
body_file_url_template: "/uploads/"
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
  issue:
    default_front_matter_template: issue
  news:
    default_front_matter_template: news
version: 0.31.1
