---
pages:
- privacy-policy.md
- events.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 
- type: image_gallery
  name: images
  label: Images
