---
label: Default
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: datetime
  hidden: false
  default: 
- type: image_gallery
  name: images
  label: Images
pages:
- content/events.md
- content/privacy-policy.md
- content/media.md
